### ISSUE TITLE
broken link on FAQ page

### ISSUE THREAD

**Issue by dschwartz-78** [reflectivity/reflectivity.github.io#17]
The hyperlink "List of reflectometers" on the [FAQ Page](https://www.reflectometry.org/information/FAQ/) points to a page that does not exist, namely https://www.reflectometry.org/information/activities.

**Comment by arm61** [comment]
Thanks for the heads up. We welcome a pull request to fix this. 

I think that on https://github.com/reflectivity/reflectivity.github.io/blob/master/information/FAQ.md

```
or see information for specific instruments available at the

  - [List of reflectometers](https://www.reflectometry.org/information/activities)
```

should be changed to 

```
or see information for specific instruments available at the

  - [List of X-ray reflectometers](https://www.reflectometry.org/information/xray_reflectometers/)
  - [List of neutron reflectometers](https://www.reflectometry.org/information/reflectometers/)
```

If you open a pull request, remember to add yourself to the `author` object at the top of the relevant page. More information about contributing can be found here https://www.reflectometry.org/information/interact_with_orso/.

**Comment by arm61** [comment]
Closing with https://github.com/reflectivity/reflectivity.github.io/commit/3dff40c6ed2eef7ef8c317774154b20963fbf5b6
