### ISSUE TITLE
Broken links on reflectometry.org 

### ISSUE THREAD

**Issue by wpotrzebowski** [reflectivity/reflectivity.github.io#20]
I've done the scan of broken links on reflectometry.org with https://www.deadlinkchecker.com/
Here is the report (formating could be nicer)
[Dead Link Checker report - http _www.reflectometry.org.pdf](https://github.com/reflectivity/reflectivity.github.io/files/8860529/Dead.Link.Checker.report.-.http._www.reflectometry.org.pdf)

**Comment by tomarnoldess** [comment]
The web-page has been completely rewritten. There may still be some links that don't work, but this report is no longer valid.
