### ISSUE TITLE
Color of links in theme is a bit subtle

### ISSUE THREAD

**Issue by bmaranville** [reflectivity/reflectivity.github.io#4]
On some screens, the difference between regular text color and link color is a little subtle.  Might be nice to up the contrast a little (or make font weight a little higher for links?)

**Comment by arm61** [comment]
Before I fix this. Do you mean the links that are [hex:2568ba](https://www.color-hex.com/color/2568ba)?

**Comment by bmaranville** [comment]
I think so - though to be honest both followed and unfollowed links are hard to see when they are inline with other text.

**Comment by arm61** [comment]
It is probably my colour deficiency that makes it very clear for me.  I have make the links 500 weight instead of 400 weight here (https://mccluskey.scot/reflectivity.github.io/working_groups/ it might not be updated yet). I did make it 700 but then they looked like headings. 

Let me know your thoughts.

**Comment by bmaranville** [comment]
That will probably help - I'm sure it's just a slightly dull monitor I'm using, but I reckon other users with non-ideal monitors will also be visiting the site.  On a Mac Retina OLED display I'm sure it's dazzling.

The default blue for e.g. links in Github issues above is much more obvious.

**Comment by arm61** [comment]
I have changed it now to colour match the GitHub link colour and reverted the font weight (it wasn't presenting 500 font weight properly anyway).

**Comment by arm61** [comment]
once it is built let me know if the visited colour should change too.

**Comment by bmaranville** [comment]
For me the github links are hex:0366d6 but agreed that the new color is more visible.

**Comment by arm61** [comment]
Possibly cause I am in Dark Mode on GitHub
